import { debug as debugInit } from "debug";
import SpotifyWebApi from "spotify-web-api-node";
import {
  BooleanColKey,
  FilterColArrayKey,
  NumericColKey,
  StringColKey,
} from "../types/fields";
import { CleanAlbum, CleanLibrary } from "./interfaces";
import { spotifyLimiter } from "./scrape/spotify";
import {
  addTracksToPlaylist,
  getUserPlaylists,
} from "./scrape/spotify-playlist";

const debug = debugInit("music-scraper:spotify-sync-playlist");

type Filter =
  | { key: Exclude<StringColKey<CleanAlbum>, undefined>; value: string }
  | { key: Exclude<NumericColKey<CleanAlbum>, undefined>; value: number }
  | { key: Exclude<BooleanColKey<CleanAlbum>, undefined>; value: boolean }
  | { key: Exclude<FilterColArrayKey<CleanAlbum>, undefined>; value: string };

type Sort =
  | { key: Exclude<StringColKey<CleanAlbum>, undefined>; desc?: boolean }
  | { key: Exclude<NumericColKey<CleanAlbum>, undefined>; desc?: boolean };

interface SyncPlaylist {
  name: string;
  filters?: Filter[];
  sort?: Sort;
  forceRecreate?: boolean;
  limit?: number;
}

export async function syncPlaylists(cleanLibrary: CleanLibrary) {
  if (process.env.SPOTIFY_TOKEN) {
    const spotifyApi = new SpotifyWebApi();
    spotifyApi.setAccessToken(process.env.SPOTIFY_TOKEN);

    debug(`connected to spotify`);

    const usersPlaylists = await getUserPlaylists(spotifyApi);

    const testPlaylist: SyncPlaylist[] = [
      // {
      //   name: "All albums",
      //   sort: { key: "dateAdded", desc: true },
      // },
      {
        name: "Ambient albums",
        filters: [{ key: "genres", value: "ambient" }],
        sort: { key: "dateAdded", desc: true },
      },
      {
        name: "Funk / soul albums",
        filters: [{ key: "genres", value: "funk / soul" }],
        sort: { key: "dateAdded", desc: true },
      },
      {
        name: "Alt rock albums (sorted by RYM)",
        filters: [{ key: "genres", value: "alternative rock" }],
        sort: { key: "ratingRymValue", desc: true },
      },
    ];

    for (let i = 0; i < testPlaylist.length; i++) {
      const playlistToSync = testPlaylist[i];
      const existingPlaylist = usersPlaylists.find(
        (p) =>
          p.name === playlistToSync.name &&
          p.description?.includes("Generated by Nick's media-scraper")
      );

      let albums = Object.values(cleanLibrary.albums);

      if (playlistToSync.filters) {
        albums = albums.filter((album) =>
          playlistToSync.filters!.reduce<boolean>((include, filter) => {
            if (!include) return false;
            const value = album[filter.key];
            if (Array.isArray(value)) {
              return value.some((element) => element === filter.value);
            }
            return value === filter.value;
          }, true)
        );
      }

      if (playlistToSync.sort) {
        albums = albums.sort((a, b) => {
          const aValue = a[playlistToSync.sort!.key];
          const bValue = b[playlistToSync.sort!.key];

          if (typeof aValue === "string" && typeof bValue === "string")
            return (aValue ?? "").localeCompare(bValue ?? "");
          if (typeof aValue === "number" && typeof bValue === "number")
            return aValue - bValue;
          return 0;
        });

        if (playlistToSync.sort?.desc) {
          albums.reverse();
        }
      }

      if (existingPlaylist && !playlistToSync.forceRecreate) {
        // Fetch and update
        console.log("TO update playlist");
      } else {
        // Create

        debug(`creating new playlist with name ${playlistToSync.name}`);
        const newPlaylist = (
          await spotifyLimiter.schedule(() =>
            spotifyApi.createPlaylist(playlistToSync.name, {
              description: `Generated by Nick's media-scraper. Last updated: ${new Date().toString()}`,
            })
          )
        ).body;
        debug(
          `successfully creating new playlist with name ${playlistToSync.name} - id = ${newPlaylist.id}\nadding ${albums.length} albums to playlist`
        );

        await addTracksToPlaylist(
          spotifyApi,
          newPlaylist.id,
          albums.reduce<string[]>(
            (tracks, album) => [...tracks, ...album.tracks],
            []
          )
        );
      }
    }
  } else {
    debug(`WARNING no SPOTIFY_TOKEN provided`);
  }
}
